# Welcome to Jekyll!
#

# Site settings
title: Marco Servidio
description: |
  A Full-stack Web Developer, IT Professional and entrepreneurâ€¦
  complemented by being an ace mixologist & Volleyball player!
owner: Marco Servidio # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: servidiomarco@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://marcoservidio.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/MarcoServidio
  github: https://github.com/servidiomarco
  linkedin-square: https://linkedin.com/in/marco-servidio-8380531b/
  # facebook-official: https://facebook.com/<username>
  # google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
